-- MySQL Script generated by MySQL Workbench
-- Sat Dec 13 18:28:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inmobiliaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inmobiliaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inmobiliaria` DEFAULT CHARACTER SET utf8 ;
USE `inmobiliaria` ;

-- -----------------------------------------------------
-- Table `inmobiliaria`.`parte_intervinente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`parte_intervinente` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`parte_intervinente` (
  `id_parte_intervinente` INT NOT NULL AUTO_INCREMENT,
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_parte_intervinente`),
  UNIQUE INDEX `id_partes_intervinentes_UNIQUE` (`id_parte_intervinente` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`locacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`locacion` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`locacion` (
  `id_locacion` INT NOT NULL AUTO_INCREMENT,
  `localidad` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero_calle` INT NOT NULL,
  `numero_dpto` INT NULL,
  PRIMARY KEY (`id_locacion`),
  UNIQUE INDEX `id_locacion_UNIQUE` (`id_locacion` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`tipo_inmueble`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`tipo_inmueble` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`tipo_inmueble` (
  `id_tipo_inmueble` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_inmueble`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`estado_inmueble`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`estado_inmueble` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`estado_inmueble` (
  `id_estado_inmueble` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado_inmueble`),
  UNIQUE INDEX `id_estado_inmueble_UNIQUE` (`id_estado_inmueble` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`inmueble`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`inmueble` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`inmueble` (
  `id_inmueble` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TINYTEXT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `precio_venta` DECIMAL NOT NULL,
  `precio_alquiler` DECIMAL NOT NULL,
  `fk_locacion` INT NOT NULL,
  `fk_tipo_inmueble` INT NOT NULL,
  `fk_estado_inmueble` INT NOT NULL,
  PRIMARY KEY (`id_inmueble`),
  UNIQUE INDEX `id_inmueble_UNIQUE` (`id_inmueble` ASC) ,
  INDEX `fk_Inmuebles_Locaciones1_idx` (`fk_locacion` ASC) ,
  INDEX `fk_inmueble_tipo_inmueble1_idx` (`fk_tipo_inmueble` ASC) ,
  INDEX `fk_inmueble_estado_inmueble1_idx` (`fk_estado_inmueble` ASC) ,
  CONSTRAINT `fk_Inmuebles_Locaciones1`
    FOREIGN KEY (`fk_locacion`)
    REFERENCES `inmobiliaria`.`locacion` (`id_locacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inmueble_tipo_inmueble1`
    FOREIGN KEY (`fk_tipo_inmueble`)
    REFERENCES `inmobiliaria`.`tipo_inmueble` (`id_tipo_inmueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inmueble_estado_inmueble1`
    FOREIGN KEY (`fk_estado_inmueble`)
    REFERENCES `inmobiliaria`.`estado_inmueble` (`id_estado_inmueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`plazo_operacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`plazo_operacion` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`plazo_operacion` (
  `id_plazo_operacion` INT NOT NULL AUTO_INCREMENT,
  `cantidad_meses` INT NOT NULL,
  PRIMARY KEY (`id_plazo_operacion`),
  UNIQUE INDEX `id_plazo_operacion_UNIQUE` (`id_plazo_operacion` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`plan_operacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`plan_operacion` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`plan_operacion` (
  `id_plan_operacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_plan_operacion`),
  UNIQUE INDEX `id_plan_operacion_UNIQUE` (`id_plan_operacion` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`operacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`operacion` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`operacion` (
  `id_operacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `monto_total` DECIMAL NOT NULL,
  `fk_inmueble` INT NOT NULL,
  `fk_plazo_operacion` INT NOT NULL,
  `fk_plan_operacion` INT NOT NULL,
  PRIMARY KEY (`id_operacion`),
  UNIQUE INDEX `id_operaciones_UNIQUE` (`id_operacion` ASC) ,
  INDEX `fk_Operaciones_Inmuebles1_idx` (`fk_inmueble` ASC) ,
  INDEX `fk_operacion_plazo_operacion1_idx` (`fk_plazo_operacion` ASC) ,
  INDEX `fk_operacion_plan_operacion1_idx` (`fk_plan_operacion` ASC) ,
  CONSTRAINT `fk_Operaciones_Inmuebles1`
    FOREIGN KEY (`fk_inmueble`)
    REFERENCES `inmobiliaria`.`inmueble` (`id_inmueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operacion_plazo_operacion1`
    FOREIGN KEY (`fk_plazo_operacion`)
    REFERENCES `inmobiliaria`.`plazo_operacion` (`id_plazo_operacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operacion_plan_operacion1`
    FOREIGN KEY (`fk_plan_operacion`)
    REFERENCES `inmobiliaria`.`plan_operacion` (`id_plan_operacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`ambiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`ambiente` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`ambiente` (
  `id_ambiente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ambiente`),
  UNIQUE INDEX `id_ambientes_UNIQUE` (`id_ambiente` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`forma_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`forma_pago` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`forma_pago` (
  `id_forma_pago` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_forma_pago`),
  UNIQUE INDEX `id_formas_pago_UNIQUE` (`id_forma_pago` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`tipo_documento` (
  `id_tipo_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_documento`),
  UNIQUE INDEX `id_tipos_Documentos_UNIQUE` (`id_tipo_documento` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`documentacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`documentacion` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`documentacion` (
  `id_documentacion` INT NOT NULL AUTO_INCREMENT,
  `fk_tipo_documento` INT NOT NULL,
  PRIMARY KEY (`id_documentacion`),
  UNIQUE INDEX `id_documentaciones_UNIQUE` (`id_documentacion` ASC) ,
  INDEX `fk_Documentaciones_Tipos_Documentos1_idx` (`fk_tipo_documento` ASC) ,
  CONSTRAINT `fk_Documentaciones_Tipos_Documentos1`
    FOREIGN KEY (`fk_tipo_documento`)
    REFERENCES `inmobiliaria`.`tipo_documento` (`id_tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`inmueble_ambiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`inmueble_ambiente` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`inmueble_ambiente` (
  `fk_inmueble` INT NOT NULL,
  `fk_ambientes` INT NOT NULL,
  `cantidad_ambientes` INT NOT NULL,
  PRIMARY KEY (`fk_inmueble`, `fk_ambientes`),
  INDEX `fk_Inmuebles_has_Ambientes_Ambientes1_idx` (`fk_ambientes` ASC) ,
  INDEX `fk_Inmuebles_has_Ambientes_Inmuebles1_idx` (`fk_inmueble` ASC) ,
  CONSTRAINT `fk_Inmuebles_has_Ambientes_Inmuebles1`
    FOREIGN KEY (`fk_inmueble`)
    REFERENCES `inmobiliaria`.`inmueble` (`id_inmueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inmuebles_has_Ambientes_Ambientes1`
    FOREIGN KEY (`fk_ambientes`)
    REFERENCES `inmobiliaria`.`ambiente` (`id_ambiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`acuerdo_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`acuerdo_pago` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`acuerdo_pago` (
  `fk_operacion` INT NOT NULL,
  `fk_forma_pago` INT NOT NULL,
  PRIMARY KEY (`fk_operacion`, `fk_forma_pago`),
  INDEX `fk_Operaciones_has_Formas_Pago_Formas_Pago1_idx` (`fk_forma_pago` ASC) ,
  INDEX `fk_Operaciones_has_Formas_Pago_Operaciones1_idx` (`fk_operacion` ASC) ,
  CONSTRAINT `fk_Operaciones_has_Formas_Pago_Operaciones1`
    FOREIGN KEY (`fk_operacion`)
    REFERENCES `inmobiliaria`.`operacion` (`id_operacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operaciones_has_Formas_Pago_Formas_Pago1`
    FOREIGN KEY (`fk_forma_pago`)
    REFERENCES `inmobiliaria`.`forma_pago` (`id_forma_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`documentacion_presentada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`documentacion_presentada` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`documentacion_presentada` (
  `fk_documentacion` INT NOT NULL,
  `fk_operacion` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`fk_documentacion`, `fk_operacion`),
  INDEX `fk_Documentaciones_has_Operaciones_Operaciones1_idx` (`fk_operacion` ASC) ,
  INDEX `fk_Documentaciones_has_Operaciones_Documentaciones1_idx` (`fk_documentacion` ASC) ,
  CONSTRAINT `fk_Documentaciones_has_Operaciones_Documentaciones1`
    FOREIGN KEY (`fk_documentacion`)
    REFERENCES `inmobiliaria`.`documentacion` (`id_documentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documentaciones_has_Operaciones_Operaciones1`
    FOREIGN KEY (`fk_operacion`)
    REFERENCES `inmobiliaria`.`operacion` (`id_operacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`tipo_garantia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`tipo_garantia` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`tipo_garantia` (
  `id_tipo_garantia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_garantia`),
  UNIQUE INDEX `id_tipos_garantias_UNIQUE` (`id_tipo_garantia` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`rol` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `id_rol_UNIQUE` (`id_rol` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`parte_operacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`parte_operacion` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`parte_operacion` (
  `fk_parte_intervinente` INT NOT NULL,
  `fk_operacion` INT NOT NULL,
  `fk_rol` INT NOT NULL,
  PRIMARY KEY (`fk_parte_intervinente`, `fk_operacion`),
  INDEX `fk_parte_intervinente_has_operacion_operacion1_idx` (`fk_operacion` ASC) ,
  INDEX `fk_parte_intervinente_has_operacion_parte_intervinente1_idx` (`fk_parte_intervinente` ASC) ,
  INDEX `fk_parte_operacion_rol1_idx` (`fk_rol` ASC) ,
  CONSTRAINT `fk_parte_intervinente_has_operacion_parte_intervinente1`
    FOREIGN KEY (`fk_parte_intervinente`)
    REFERENCES `inmobiliaria`.`parte_intervinente` (`id_parte_intervinente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parte_intervinente_has_operacion_operacion1`
    FOREIGN KEY (`fk_operacion`)
    REFERENCES `inmobiliaria`.`operacion` (`id_operacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parte_operacion_rol1`
    FOREIGN KEY (`fk_rol`)
    REFERENCES `inmobiliaria`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`rol_has_parte_operacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`rol_has_parte_operacion` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`rol_has_parte_operacion` (
  `rol_id_rol` INT NOT NULL,
  `parte_operacion_fk_parte_intervinente` INT NOT NULL,
  `parte_operacion_fk_operacion` INT NOT NULL,
  PRIMARY KEY (`rol_id_rol`, `parte_operacion_fk_parte_intervinente`, `parte_operacion_fk_operacion`),
  INDEX `fk_rol_has_parte_operacion_parte_operacion1_idx` (`parte_operacion_fk_parte_intervinente` ASC, `parte_operacion_fk_operacion` ASC) ,
  INDEX `fk_rol_has_parte_operacion_rol1_idx` (`rol_id_rol` ASC) ,
  CONSTRAINT `fk_rol_has_parte_operacion_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `inmobiliaria`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_has_parte_operacion_parte_operacion1`
    FOREIGN KEY (`parte_operacion_fk_parte_intervinente` , `parte_operacion_fk_operacion`)
    REFERENCES `inmobiliaria`.`parte_operacion` (`fk_parte_intervinente` , `fk_operacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`monto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`monto` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`monto` (
  `id_monto` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_monto`),
  UNIQUE INDEX `id_monto_UNIQUE` (`id_monto` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`tipo_plazo_operacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`tipo_plazo_operacion` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`tipo_plazo_operacion` (
  `id_tipo_plazo_operacion` INT NOT NULL,
  PRIMARY KEY (`id_tipo_plazo_operacion`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Data for table `inmobiliaria`.`parte_intervinente`
-- -----------------------------------------------------
START TRANSACTION;
USE `inmobiliaria`;
INSERT INTO `inmobiliaria`.`parte_intervinente` (`id_parte_intervinente`, `dni`, `nombre`, `telefono`, `fecha_nacimiento`, `email`, `apellido`) VALUES (1, 1, 'marcos', 23, '2007-06-26', 'marcos@gmail.com', 'di filippo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inmobiliaria`.`tipo_inmueble`
-- -----------------------------------------------------
START TRANSACTION;
USE `inmobiliaria`;
INSERT INTO `inmobiliaria`.`tipo_inmueble` (`id_tipo_inmueble`, `nombre`) VALUES (1, 'Departamento');
INSERT INTO `inmobiliaria`.`tipo_inmueble` (`id_tipo_inmueble`, `nombre`) VALUES (2, 'Casa');
INSERT INTO `inmobiliaria`.`tipo_inmueble` (`id_tipo_inmueble`, `nombre`) VALUES (3, 'Cancha');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inmobiliaria`.`estado_inmueble`
-- -----------------------------------------------------
START TRANSACTION;
USE `inmobiliaria`;
INSERT INTO `inmobiliaria`.`estado_inmueble` (`id_estado_inmueble`, `nombre`) VALUES (1, 'excelente');
INSERT INTO `inmobiliaria`.`estado_inmueble` (`id_estado_inmueble`, `nombre`) VALUES (2, 'muy bueno');
INSERT INTO `inmobiliaria`.`estado_inmueble` (`id_estado_inmueble`, `nombre`) VALUES (3, 'bueno');
INSERT INTO `inmobiliaria`.`estado_inmueble` (`id_estado_inmueble`, `nombre`) VALUES (4, 'a refaccionar');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inmobiliaria`.`plazo_operacion`
-- -----------------------------------------------------
START TRANSACTION;
USE `inmobiliaria`;
INSERT INTO `inmobiliaria`.`plazo_operacion` (`id_plazo_operacion`, `cantidad_meses`) VALUES (1, 12);
INSERT INTO `inmobiliaria`.`plazo_operacion` (`id_plazo_operacion`, `cantidad_meses`) VALUES (2, 24);
INSERT INTO `inmobiliaria`.`plazo_operacion` (`id_plazo_operacion`, `cantidad_meses`) VALUES (3, 36);
INSERT INTO `inmobiliaria`.`plazo_operacion` (`id_plazo_operacion`, `cantidad_meses`) VALUES (4, 48);
INSERT INTO `inmobiliaria`.`plazo_operacion` (`id_plazo_operacion`, `cantidad_meses`) VALUES (5, 60);

COMMIT;


-- -----------------------------------------------------
-- Data for table `inmobiliaria`.`plan_operacion`
-- -----------------------------------------------------
START TRANSACTION;
USE `inmobiliaria`;
INSERT INTO `inmobiliaria`.`plan_operacion` (`id_plan_operacion`, `nombre`) VALUES (1, 'Cuatrimestral');
INSERT INTO `inmobiliaria`.`plan_operacion` (`id_plan_operacion`, `nombre`) VALUES (2, 'Semestral');
INSERT INTO `inmobiliaria`.`plan_operacion` (`id_plan_operacion`, `nombre`) VALUES (3, 'Anual');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inmobiliaria`.`ambiente`
-- -----------------------------------------------------
START TRANSACTION;
USE `inmobiliaria`;
INSERT INTO `inmobiliaria`.`ambiente` (`id_ambiente`, `nombre`) VALUES (1, 'Cocina');
INSERT INTO `inmobiliaria`.`ambiente` (`id_ambiente`, `nombre`) VALUES (2, 'Baño');
INSERT INTO `inmobiliaria`.`ambiente` (`id_ambiente`, `nombre`) VALUES (3, 'Cochera');
INSERT INTO `inmobiliaria`.`ambiente` (`id_ambiente`, `nombre`) VALUES (4, 'Habitacion');
INSERT INTO `inmobiliaria`.`ambiente` (`id_ambiente`, `nombre`) VALUES (5, 'Living');
INSERT INTO `inmobiliaria`.`ambiente` (`id_ambiente`, `nombre`) VALUES (6, 'Patio');
INSERT INTO `inmobiliaria`.`ambiente` (`id_ambiente`, `nombre`) VALUES (7, 'Terraza');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inmobiliaria`.`forma_pago`
-- -----------------------------------------------------
START TRANSACTION;
USE `inmobiliaria`;
INSERT INTO `inmobiliaria`.`forma_pago` (`id_forma_pago`, `tipo`) VALUES (1, 'Efectivo');
INSERT INTO `inmobiliaria`.`forma_pago` (`id_forma_pago`, `tipo`) VALUES (2, 'Transferencia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inmobiliaria`.`tipo_documento`
-- -----------------------------------------------------
START TRANSACTION;
USE `inmobiliaria`;
INSERT INTO `inmobiliaria`.`tipo_documento` (`id_tipo_documento`, `nombre`) VALUES (1, 'Documento Identificacion');
INSERT INTO `inmobiliaria`.`tipo_documento` (`id_tipo_documento`, `nombre`) VALUES (2, 'Recibo Sueldo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inmobiliaria`.`rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `inmobiliaria`;
INSERT INTO `inmobiliaria`.`rol` (`id_rol`, `nombre`) VALUES (1, 'Propietario');
INSERT INTO `inmobiliaria`.`rol` (`id_rol`, `nombre`) VALUES (2, 'Inquilino');
INSERT INTO `inmobiliaria`.`rol` (`id_rol`, `nombre`) VALUES (3, 'Garante');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
